// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayrollAPI.Data;

#nullable disable

namespace PayrollAPI.Migrations
{
    [DbContext(typeof(PayrollDbContext))]
    [Migration("20260915073225_SeedTaxYear2024Test")]
    partial class SeedTaxYear2024Test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PayrollAPI.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GrossMonthlySalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UifExempt")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PayrollAPI.Models.TaxBracket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TaxYearId")
                        .HasColumnType("int");

                    b.Property<decimal>("Threshold")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TaxYearId");

                    b.ToTable("TaxBrackets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseTax = 0m,
                            Rate = 0.18m,
                            TaxYearId = 1,
                            Threshold = 0m
                        },
                        new
                        {
                            Id = 2,
                            BaseTax = 44118m,
                            Rate = 0.26m,
                            TaxYearId = 1,
                            Threshold = 245100m
                        },
                        new
                        {
                            Id = 3,
                            BaseTax = 79998m,
                            Rate = 0.31m,
                            TaxYearId = 1,
                            Threshold = 383100m
                        },
                        new
                        {
                            Id = 4,
                            BaseTax = 125599m,
                            Rate = 0.36m,
                            TaxYearId = 1,
                            Threshold = 530200m
                        },
                        new
                        {
                            Id = 5,
                            BaseTax = 185215m,
                            Rate = 0.39m,
                            TaxYearId = 1,
                            Threshold = 695800m
                        },
                        new
                        {
                            Id = 6,
                            BaseTax = 259783m,
                            Rate = 0.41m,
                            TaxYearId = 1,
                            Threshold = 887000m
                        },
                        new
                        {
                            Id = 7,
                            BaseTax = 666339m,
                            Rate = 0.45m,
                            TaxYearId = 1,
                            Threshold = 1878600m
                        },
                        new
                        {
                            Id = 8,
                            BaseTax = 0m,
                            Rate = 0.18m,
                            TaxYearId = 2,
                            Threshold = 0m
                        });
                });

            modelBuilder.Entity("PayrollAPI.Models.TaxYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrimaryRebate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SdlAnnualThreshold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SdlRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UifCeiling")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UifRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TaxYears");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EffectiveFrom = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveTo = new DateTime(2027, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Label = "2026/27",
                            PrimaryRebate = 17820m,
                            SdlAnnualThreshold = 500000m,
                            SdlRate = 0.01m,
                            UifCeiling = 17712m,
                            UifRate = 0.01m
                        },
                        new
                        {
                            Id = 2,
                            EffectiveFrom = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveTo = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Label = "2024/25 (test)",
                            PrimaryRebate = 17235m,
                            SdlAnnualThreshold = 500000m,
                            SdlRate = 0.01m,
                            UifCeiling = 5000m,
                            UifRate = 0.01m
                        });
                });

            modelBuilder.Entity("PayrollAPI.Models.TaxBracket", b =>
                {
                    b.HasOne("PayrollAPI.Models.TaxYear", "TaxYear")
                        .WithMany("Brackets")
                        .HasForeignKey("TaxYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaxYear");
                });

            modelBuilder.Entity("PayrollAPI.Models.TaxYear", b =>
                {
                    b.Navigation("Brackets");
                });
#pragma warning restore 612, 618
        }
    }
}
